#
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-arm
spec:
  version: 8.4.2
  nodeSets:
  # 2 dedicated master nodes
  - name: master
    count: 3
    config:
      node.roles: ["master"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2Gi
              #
  - name: master-votingonly
    count: 3
    config:
      node.roles: ["master", "voting_only"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2Gi
#
  # 2 ingest-data nodes
  - name: ingest-data
    count: 2
    config:
      node.roles: ["data", "ingest"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 4
            limits:
              memory: 4Gi


