POST https://container.googleapis.com/v1beta1/projects/elastic-sa/locations/us-central1/clusters
{
  "cluster": {
    "name": "vestal-gke-clone-1",
    "masterAuth": {
      "clientCertificateConfig": {}
    },
    "network": "projects/elastic-sa/global/networks/vestal-vpc",
    "addonsConfig": {
      "httpLoadBalancing": {},
      "horizontalPodAutoscaling": {},
      "kubernetesDashboard": {
        "disabled": true
      },
      "dnsCacheConfig": {},
      "gcePersistentDiskCsiDriverConfig": {
        "enabled": true
      }
    },
    "subnetwork": "projects/elastic-sa/regions/us-central1/subnetworks/vestal-vpc",
    "nodePools": [
      {
        "name": "default-pool",
        "config": {
          "machineType": "n2-standard-2",
          "diskSizeGb": 100,
          "oauthScopes": [
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/servicecontrol",
            "https://www.googleapis.com/auth/service.management.readonly",
            "https://www.googleapis.com/auth/trace.append"
          ],
          "metadata": {
            "disable-legacy-endpoints": "true"
          },
          "imageType": "COS_CONTAINERD",
          "localSsdCount": 1,
          "diskType": "pd-balanced",
          "shieldedInstanceConfig": {
            "enableIntegrityMonitoring": true
          }
        },
        "initialNodeCount": 1,
        "autoscaling": {},
        "management": {
          "autoUpgrade": true,
          "autoRepair": true
        },
        "maxPodsConstraint": {
          "maxPodsPerNode": "110"
        },
        "networkConfig": {},
        "upgradeSettings": {
          "maxSurge": 1
        }
      },
      {
        "name": "spinning",
        "config": {
          "machineType": "e2-medium",
          "diskSizeGb": 50,
          "oauthScopes": [
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/servicecontrol",
            "https://www.googleapis.com/auth/service.management.readonly",
            "https://www.googleapis.com/auth/trace.append"
          ],
          "metadata": {
            "disable-legacy-endpoints": "true"
          },
          "imageType": "COS_CONTAINERD",
          "diskType": "pd-balanced",
          "shieldedInstanceConfig": {
            "enableIntegrityMonitoring": true
          }
        },
        "initialNodeCount": 1,
        "autoscaling": {},
        "management": {
          "autoUpgrade": true,
          "autoRepair": true
        },
        "maxPodsConstraint": {
          "maxPodsPerNode": "110"
        },
        "networkConfig": {},
        "upgradeSettings": {
          "maxSurge": 1
        }
      }
    ],
    "locations": [
      "us-central1-a",
      "us-central1-b",
      "us-central1-f"
    ],
    "networkPolicy": {},
    "ipAllocationPolicy": {
      "useIpAliases": true
    },
    "masterAuthorizedNetworksConfig": {},
    "binaryAuthorization": {
      "evaluationMode": "DISABLED"
    },
    "autoscaling": {},
    "networkConfig": {
      "datapathProvider": "LEGACY_DATAPATH"
    },
    "defaultMaxPodsConstraint": {
      "maxPodsPerNode": "110"
    },
    "authenticatorGroupsConfig": {},
    "databaseEncryption": {
      "state": "DECRYPTED"
    },
    "shieldedNodes": {
      "enabled": true
    },
    "releaseChannel": {
      "channel": "REGULAR"
    },
    "notificationConfig": {
      "pubsub": {}
    },
    "initialClusterVersion": "1.24.2-gke.1900",
    "location": "us-central1",
    "loggingConfig": {
      "componentConfig": {
        "enableComponents": [
          "SYSTEM_COMPONENTS",
          "WORKLOADS"
        ]
      }
    },
    "monitoringConfig": {
      "componentConfig": {
        "enableComponents": [
          "SYSTEM_COMPONENTS"
        ]
      }
    }
  }
}
